### ISSUE TITLE
[TODO LIST]

### ISSUE THREAD

**Issue by ahmadxgani** [SeishinKeiji/next-blog-frontend#1]
### Pending

- [ ] Using the apollo cache to toggle the mark on liked posts, instead of checking with the GraphQL server 
- [ ] readonly for all input field on submit
- [ ] dilemma: use redirect hooks in logout function and get benefit of remove unnecessary query or use resetStore to trigger refetch and got auto redirect by wrap the authenticated page, [ref](https://github.com/apollographql/apollo-client/issues/8995)
